synthetic-package: false

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false

output-dir: lib/src/generated/i10n
untranslated-messages-file: lib/src/generated/desiredFileName.txt