name: base_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  adaptive_theme: ^3.7.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_appauth: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  ntp: ^2.0.0
  responsive_framework: ^1.5.1
  skeletonizer: ^1.4.3
  toastification: ^3.0.2
  flutter_flavor: ^3.1.4
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  logger: ^2.5.0
  lottie: ^3.3.1
  flutter_tabler_icons: ^1.43.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner:
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
